name = "QuarticSolver"
uuid = "efd27559-0196-40c1-9d2a-48dcd51f8c0a"
authors = ["Forrest Gasdia <EP-Guy@users.noreply.github.com>"]
version = "0.1.0"

[deps]
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
